"""initial migration

Revision ID: d3e57c90f6d3
Revises: 
Create Date: 2026-03-22 14:05:10.559653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e57c90f6d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('shortcut', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('energy_tariff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pass', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pkwiu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkwiu_nr', sa.String(length=10), nullable=False),
    sa.Column('pkwiu_name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shortcut', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcut')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=100), nullable=True),
    sa.Column('building_nr', sa.Integer(), nullable=True),
    sa.Column('apartment_nr', sa.Integer(), nullable=True),
    sa.Column('post_code', sa.String(length=20), nullable=True),
    sa.Column('id_city', sa.Integer(), nullable=True),
    sa.Column('id_district', sa.Integer(), nullable=True),
    sa.Column('id_country', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_city'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['id_country'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['id_district'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.Column('id_tariff', sa.Integer(), nullable=False),
    sa.Column('id_power_unit', sa.Integer(), nullable=True),
    sa.Column('id_currency_unit', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_currency_unit'], ['currency_unit.id'], ),
    sa.ForeignKeyConstraint(['id_power_unit'], ['power_unit.id'], ),
    sa.ForeignKeyConstraint(['id_supplier'], ['energy_supplier.id'], ),
    sa.ForeignKeyConstraint(['id_tariff'], ['energy_tariff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_pass', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_pass'], ['password.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_pass'),
    sa.UniqueConstraint('username')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=12), nullable=True),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('pesel', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.String(length=20), nullable=True),
    sa.Column('nip', sa.String(length=20), nullable=True),
    sa.Column('regon', sa.Integer(), nullable=True),
    sa.Column('id_pkwiu', sa.Integer(), nullable=True),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('private_or_company', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_pkwiu'], ['pkwiu.id'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_who_changed', sa.String(length=12), nullable=True),
    sa.Column('id_role', sa.Integer(), nullable=True),
    sa.Column('id_action', sa.Integer(), nullable=True),
    sa.Column('change_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_action'], ['action.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['role.id'], ),
    sa.ForeignKeyConstraint(['id_user_who_changed'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.Column('id_supplier', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['id_supplier'], ['energy_supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_supplier')
    )
    op.create_table('user_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_who_changed', sa.String(length=12), nullable=True),
    sa.Column('id_user_changed', sa.String(length=12), nullable=True),
    sa.Column('id_action', sa.Integer(), nullable=True),
    sa.Column('change_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_action'], ['action.id'], ),
    sa.ForeignKeyConstraint(['id_user_changed'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_user_who_changed'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_log_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=12), nullable=True),
    sa.Column('id_action', sa.Integer(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_action'], ['action.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('sales_rep_id', sa.String(length=12), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['sales_rep_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'sales_rep_id', name='uq_assignment_customer_salesrep')
    )
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.String(length=12), nullable=True),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(length=150), nullable=False),
    sa.Column('signed_at', sa.Date(), nullable=True),
    sa.Column('contract_from', sa.Date(), nullable=True),
    sa.Column('contract_to', sa.Date(), nullable=True),
    sa.Column('id_supplier_offer', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['id_supplier_offer'], ['supplier_offer.id'], ),
    sa.ForeignKeyConstraint(['id_tag'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_customer')
    )
    op.create_table('ppe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_customer', sa.Integer(), nullable=False),
    sa.Column('id_address', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_address'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['id_customer'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_contract', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_contract'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_timeline')
    op.drop_table('ppe')
    op.drop_table('customer_address')
    op.drop_table('contract')
    op.drop_table('assignments')
    op.drop_table('user_log_history')
    op.drop_table('user_change_history')
    op.drop_table('supplier_address')
    op.drop_table('role_change_history')
    op.drop_table('customer')
    op.drop_table('user')
    op.drop_table('supplier_offer')
    op.drop_table('addresses')
    op.drop_table('tag')
    op.drop_table('role')
    op.drop_table('power_unit')
    op.drop_table('pkwiu')
    op.drop_table('password')
    op.drop_table('energy_tariff')
    op.drop_table('energy_supplier')
    op.drop_table('districts')
    op.drop_table('currency_unit')
    op.drop_table('countries')
    op.drop_table('cities')
    op.drop_table('action')
    # ### end Alembic commands ###
